//! NodeForge 核心库入口。
//! 统一导出配置事实模型、校验器和服务实现，业务模块不得重复定义影子结构。

pub const model = @import("model.zig");
pub const paths = @import("paths.zig");
pub const version = @import("version.zig");
pub const catalog = @import("catalog.zig");
pub const catalog_store = @import("catalog/store.zig");
pub const iso_import = @import("catalog/iso_import.zig");
pub const app = @import("app.zig");
pub const config = @import("config/load.zig");
pub const config_store = @import("config/store.zig");
pub const config_validate = @import("config/validate.zig");
pub const preflight = @import("preflight.zig");
pub const runtime_state = @import("state/runtime.zig");
pub const boot_session = @import("state/boot_session.zig");
pub const node_status = @import("state/node_status.zig");
pub const catalog_runtime = @import("state/catalog_runtime.zig");
pub const events = @import("state/events.zig");
pub const event_types = @import("state/event_types.zig");
pub const dhcp_store = @import("state/dhcp_store.zig");
pub const management_client = @import("http/client.zig");
pub const management = @import("http/management.zig");
pub const http_server = @import("http/server.zig");
pub const http_contracts = @import("http/contracts.zig");
pub const http_auth = @import("http/auth.zig");
pub const tftp_packet = @import("tftp/packet.zig");
pub const tftp_server = @import("tftp/server.zig");
pub const dhcp_packet = @import("dhcp/packet.zig");
pub const dhcp_probe = @import("dhcp/probe.zig");
pub const dhcp_server = @import("dhcp/server.zig");
pub const boot_resolver = @import("boot/resolver.zig");
pub const asset_validate = @import("assets/validate.zig");
pub const grub = @import("boot/grub.zig");
pub const observe_error = @import("observe/error.zig");
pub const observe_log = @import("observe/log.zig");
pub const log_backend = @import("observe/log_backend.zig");
pub const cli_table = @import("cli/table.zig");
pub const cli_output = @import("cli/output.zig");
pub const cli_views = @import("cli/views.zig");
pub const cli_events = @import("cli/events.zig");

test {
    _ = model;
    _ = paths;
    _ = version;
    _ = catalog;
    _ = catalog_store;
    _ = iso_import;
    _ = app;
    _ = config;
    _ = config_store;
    _ = config_validate;
    _ = preflight;
    _ = runtime_state;
    _ = boot_session;
    _ = node_status;
    _ = catalog_runtime;
    _ = events;
    _ = event_types;
    _ = dhcp_store;
    _ = management_client;
    _ = management;
    _ = http_server;
    _ = http_contracts;
    _ = http_auth;
    _ = tftp_packet;
    _ = tftp_server;
    _ = dhcp_packet;
    _ = dhcp_probe;
    _ = dhcp_server;
    _ = boot_resolver;
    _ = asset_validate;
    _ = grub;
    _ = observe_error;
    _ = observe_log;
    _ = log_backend;
    _ = cli_table;
    _ = cli_output;
    _ = cli_views;
    _ = cli_events;
}
const std = @import("std");
const log_backend_impl = @import("observe/log_backend.zig");

pub const std_options: std.Options = .{ .log_level = .debug, .logFn = log_backend_impl.logFn };
